### ISSUE TITLE
No matching distribution found for python-apt==1.1.0b5

### ISSUE THREAD

**Issue by Okwas** [Ruud14/SecurityCamera#4]
I get this message when I try to run "pip3 install -r requirements.txt" command. Is there any way to fix this?
![error2](https://user-images.githubusercontent.com/23138643/126170379-5a5b9cff-74ee-4320-826e-414434df7f3f.png)

**Comment by Ruud14** [comment]
It seems that installing python-apt through pip is no longer supported. 
I'd recommend you to try and run `pip3 install -r requirements.txt` after removing the line `python-apt==1.1.0b5` from requirements.txt.

If that doesn't work, try to install python-apt by using `sudo apt install python3-apt apt`.

Please let me know which one (if any) of these solutions worked so I can change the documentation.

**Comment by benlemasurier** [comment]
`git rev-parse HEAD`->
 0815a81d1b0e6d7c0aa65e9aff6cecdb468beddd

```
$ git diff requirements.txt
diff --git a/requirements.txt b/requirements.txt
index 2d7b1fd..2eba986 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -1,7 +1,6 @@
 chardet==2.3.0
 numpy==1.16.4
 picamera==1.13
-python-apt==1.1.0b5
 requests==2.20.0
 six==1.12.0
 ssh-import-id==5.6
 ```
 
 ```
 $ pip3 install -r requirements.txt
[...]
Successfully installed chardet-2.3.0 numpy-1.16.4 picamera-1.13 requests-2.20.0 ssh-import-id-5.6 tornado-6.1 urllib3-1.26.5
 ```
 
 ```
 $ python3 ./main.py
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/core/__init__.py", line 40, in <module>
    from . import multiarray
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory
 ```
 
 ```
 $ sudo apt-get install libatlas-base-dev
 ```
 :shipit:

**Comment by Ruud14** [comment]
Fixed as of https://github.com/Ruud14/SecurityCamera/commit/665933986ced36d6ea1cda391de0df8616c9a2fa
