### ISSUE TITLE
Consider adding a license.

### ISSUE THREAD

**Issue by NightShade256** [Ruud14/SecurityCamera#9]
Hi,

I recently came across this repository and would like to modify and use some bits and pieces of it, but due to there being no clear licensing scheme I cannot. Therefore, I would request you to please consider adding a license.

**Comment by Ruud14** [comment]
Hi, 

Thanks for the suggestion, I added an MIT license!

Have a good one!

**Comment by NightShade256** [comment]
Thank you for responding so quickly, and accepting my request!
